name: Build and publish to gh pages

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '12 * * * *'
    - cron: '42 * * * *'
  
env:
  ASPNETCORE_ENVIRONMENT: Production
  WEBAPP_PATH: ./
  WEBAPP_CSPROJ: BlazorStaticMinimalBlog.csproj

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Set timezone to PH (UTC +8)
        uses: MathRobin/timezone-action@v1.1
        with:
             timezoneLinux: 'Asia/Manila'
             timezoneMacos: 'Asia/Manila'
             timezoneWindows: 'Singapore Standard Time'
             
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
              dotnet-version: 9.0.x

      - name: Remove launchSettings.json (to not override ASPNETCORE_ENVIRONMENT)
        run: rm  ${{ env.WEBAPP_PATH }}Properties/launchSettings.json

      - name: Change <base href="" /> in App.razor to match GitHub repo name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $NF}')
          if [[ "$REPO_NAME" != *.github.io ]]; then
            sed -i 's|<base href="/" />|<base href="/'$REPO_NAME'/" />|g' ${{ env.WEBAPP_PATH }}/Components/App.razor
          fi
          
      - name: Run webapp and generate static files
        run: |
          dotnet run --project ${{ env.WEBAPP_PATH }}${{env.WEBAPP_CSPROJ}}  --configuration Release
          
      - name: Handle default Jekyll behaviour
        run: touch ${{ env.WEBAPP_PATH }}/output/.nojekyll #folder starting with _ are handled as jekyll. This file will prevent that.  
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.WEBAPP_PATH }}output
