name: Build, PDF-export & publish to GH Pages

on:
  push:
    branches: [ "*" ]

env:
  ASPNETCORE_ENVIRONMENT: Production
  WEBAPP_PATH: ./
  WEBAPP_CSPROJ: BlazorStaticMinimalBlog.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      html-files: ${{ steps.find_html.outputs.files }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Build static site
        run: dotnet run --project ${{ env.WEBAPP_PATH }}${{ env.WEBAPP_CSPROJ }} --configuration Release

      - name: Find all blog HTML files
        id: find_html
        run: |
          # Collect only the filenames (not full paths)
          files=$(find output/blog -name '*.html' -printf "%f\n" | jq -R . | jq -s .)
          echo "files=$files" >> $GITHUB_OUTPUT

  generate-pdfs:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.build.outputs.html-files) }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate PDF for ${{ matrix.file }}
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: output/blog/${{ matrix.file }}
          outputFile: pdf/${{ matrix.file/.html/.pdf }}
          pdfOptions: '{"format":"A4","margin":{"top":"10mm","left":"10mm","right":"10mm","bottom":"10mm"}}'

  deploy:
    needs: [build, generate-pdfs]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: |
            output
            pdf
